[package]
name = "server"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["api", "entity", "migration", "service"]

[dependencies]
api = {path = "api"}
chrono = { version = "0.4.38", features = ["serde"] }
uuid = { version = "1.8.0", features = ["v4", "serde", "fast-rng"] }
